### ISSUE TITLE
please add support for CSS

### ISSUE THREAD

**Issue by majewsky** [ciaranm/detectindent#14]
CSS has C-style block comments `/* ... */` only.

**Comment by xaviervalarino** [comment]
@majewsky Are you describing what I have been experiencing when running `DetectIndent` on a CSS file?

When run on a file with multiline block comments, _i.e._,

``` css
/*
 * CSS Multi-line comment
 * ===================================
 * Description about the class
 */

.described-class {
    position: relative;
}
```

it returns an `softtabstop` and `shiftwidth` of 1.
